
networks:
  traefik_proxy:
    external: true
  cloudflare-transport:

include:
# Infrastructure Services
  - ./infrastructure/watchtower/watchtower.yaml
  - ./infrastructure/cloudflared/cloudflared.yaml

# Monitoring Services
  - ./monitoring/grafana/grafana.yaml
  - ./monitoring/prometheus/prometheus.yaml

# Network Services
  - ./networking/traefik/traefik.yaml
  - ./networking/pihole/pihole.yaml

# Management Services
  - ./management/portainer/portainer.yaml

# Family Services
  - ./mealie/mealie.yaml

# Media Services
  - ./media/sonarr/sonarr.yaml
  - ./media/radarr/radarr.yaml
  - ./media/hydra2/hydra.yaml
  - ./media/sabnzbd/sabnzbd.yaml
# - ./media/docker-compose.yaml

# AI
  - ./ollama/ollama.yaml






