
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - "${CONFIG_VOLUME}/jellyfin:/config"
      - "${MEDIA_VOLUME}/:/media"
    ports:
      - ${JELLYFIN_PORT}:8096
    environment:
      - PUID: ${UID}
      - PGID: ${GUID}
      - TZ: ${TZ}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)'
      - 'traefik.http.routers.jellyfin.entrypoints=https'
      - 'traefik.http.routers.jellyfin.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.jellyfin.tls.domains[0].main=${DOMAIN}'
      - 'traefik.http.routers.jellyfin.tls.domains[0].sans=*.${DOMAIN}'
      - 'traefik.http.services.jellyfin.loadbalancer.server.port=8096'
      - 'traefik.docker.network=traefik_proxy'
    networks:
      - traefik_proxy
    restart: unless-stopped

networks:
  traefik_proxy:
    external: true